POST  http://localhost:8888/.netlify/functions/api/
Content-Type: application/json

{
    "name":"hanka",
    "email": "hanka@gmail.com",
    "payingSystem": "MPS",
    "availableCodes":[
          {
            "videoID" : "videotwo",
            "code":"dsdabdosdds"
            }
        ]
        
}

###
GET http://localhost:8888/.netlify/functions/api/sdf@mliok.com

###
GET http://localhost:8888/.netlify/functions/api/

###
DELETE http://localhost:8888/.netlify/functions/api/bahget@gmail.com

###
PATCH http://localhost:8888/.netlify/functions/api/hanka@gmail.com
Content-Type: application/json

{
    "availableCodes":{
            "videoID" : "videotwo",
            "code":"ddrtytyn"
    }
        
}