POST https://hany-server.netlify.app/.netlify/functions/api/codes/Algebra/
Content-Type: application/json

{
    "order": "algebra15",
    "code": [
        
    ]
}


###

GET https://hany-server.netlify.app/.netlify/functions/api/Algebra/getAll

###